using System.Text;

namespace Clet;

/// <summary>
/// Strips terminal escape sequences from untrusted content before it reaches the terminal driver.
/// Removes ESC (\x1b), BEL (\x07), 8-bit CSI (\x9b), 8-bit OSC (\x9d), and C1 7-bit pairs
/// (\x1b@ through \x1b_) to prevent OSC clipboard hijack, window-title rewrite, link spoofing,
/// and other terminal-state abuses.
/// </summary>
/// <remarks>
/// See D-030 in specs/decisions.md for the rationale behind filtering at the clet layer
/// rather than relying on Terminal.Gui.
/// </remarks>
internal static class TerminalEscapeSanitizer
{
    /// <summary>
    /// Sanitizes user-supplied content by removing dangerous terminal control sequences.
    /// This method is safe to call on content that will be handed to Terminal.Gui views
    /// or rendered to ANSI output.
    /// </summary>
    /// <param name="input">The untrusted input string (may be null).</param>
    /// <returns>The sanitized string with all dangerous control codes removed, or null if input was null.</returns>
    public static string? Sanitize (string? input)
    {
        if (input is null)
        {
            return null;
        }

        if (input.Length == 0)
        {
            return string.Empty;
        }

        // Single-pass: scan and only allocate StringBuilder when the first dangerous byte is found
        StringBuilder? sb = null;

        for (int i = 0; i < input.Length; i++)
        {
            char c = input[i];

            switch (c)
            {
                case '\x1b': // ESC
                    sb ??= new StringBuilder (input.Length).Append (input, 0, i);

                    // Check for C1 7-bit pair: ESC followed by @ through _
                    if (i + 1 < input.Length && input[i + 1] >= '@' && input[i + 1] <= '_')
                    {
                        // Skip the ESC and the following character (C1 7-bit pair)
                        i++;
                    }

                    // Otherwise just strip the bare ESC
                    break;

                case '\x07': // BEL
                case '\x9b': // 8-bit CSI
                case '\x9d': // 8-bit OSC
                    sb ??= new StringBuilder (input.Length).Append (input, 0, i);

                    // Strip these single-byte controls
                    break;

                default:
                    sb?.Append (c);

                    break;
            }
        }

        return sb?.ToString () ?? input;
    }

    /// <summary>
    /// Strips user-payload escape sequences from ANSI renderer output while preserving
    /// legitimate SGR sequences generated by the renderer itself.
    /// </summary>
    /// <remarks>
    /// The MarkdownHelpRenderer legitimately produces ANSI SGR sequences (color, bold, etc.)
    /// via Terminal.Gui's ANSI driver. However, user content embedded in the markdown could
    /// smuggle through dangerous OSC/C1 sequences. This method strips only the dangerous
    /// sequences (BEL, 8-bit CSI/OSC, bare non-SGR ESC sequences) while preserving
    /// standard SGR (\x1b[...m) and cursor/erase sequences the renderer needs.
    /// </remarks>
    /// <param name="renderedAnsi">The ANSI output from the renderer.</param>
    /// <returns>The output with dangerous escape sequences removed.</returns>
    public static string SanitizeRenderedOutput (string renderedAnsi)
    {
        if (string.IsNullOrEmpty (renderedAnsi))
        {
            return string.Empty;
        }

        // Single-pass: scan and only allocate StringBuilder when the first dangerous byte is found
        StringBuilder? sb = null;

        for (int i = 0; i < renderedAnsi.Length; i++)
        {
            char c = renderedAnsi[i];

            switch (c)
            {
                case '\x1b':
                    if (i + 1 < renderedAnsi.Length)
                    {
                        char next = renderedAnsi[i + 1];

                        if (next == '[')
                        {
                            // CSI sequence — this is legitimate renderer output (SGR, cursor, erase)
                            // Pass through the entire sequence up to the terminating byte (0x40-0x7E)
                            sb?.Append ('\x1b');
                            sb?.Append ('[');
                            i += 2;

                            while (i < renderedAnsi.Length)
                            {
                                char seqChar = renderedAnsi[i];
                                sb?.Append (seqChar);

                                // CSI terminates at bytes 0x40–0x7E
                                if (seqChar is >= '@' and <= '~')
                                {
                                    break;
                                }

                                i++;
                            }
                        }
                        else if (next == ']')
                        {
                            // OSC sequence (ESC ]). Preserve OSC 8 (hyperlinks) — they're
                            // legitimate renderer output for terminals that support them.
                            // Strip all other OSC sequences.
                            if (i + 2 < renderedAnsi.Length && renderedAnsi[i + 2] == '8')
                            {
                                // OSC 8 hyperlink — pass through until ST (ESC \ or BEL)
                                sb?.Append ('\x1b');
                                sb?.Append (']');
                                i += 2;

                                while (i < renderedAnsi.Length)
                                {
                                    char osc = renderedAnsi[i];

                                    if (osc == '\x07')
                                    {
                                        // BEL terminates OSC
                                        sb?.Append (osc);

                                        break;
                                    }

                                    if (osc == '\x1b' && i + 1 < renderedAnsi.Length && renderedAnsi[i + 1] == '\\')
                                    {
                                        // ST (ESC \) terminates OSC
                                        sb?.Append ('\x1b');
                                        sb?.Append ('\\');
                                        i++;

                                        break;
                                    }

                                    sb?.Append (osc);
                                    i++;
                                }
                            }
                            else
                            {
                                // Non-hyperlink OSC — dangerous, strip it
                                sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);
                                i += 2;

                                while (i < renderedAnsi.Length)
                                {
                                    char osc = renderedAnsi[i];

                                    if (osc == '\x07')
                                    {
                                        break;
                                    }

                                    if (osc == '\x1b' && i + 1 < renderedAnsi.Length && renderedAnsi[i + 1] == '\\')
                                    {
                                        i++;

                                        break;
                                    }

                                    i++;
                                }
                            }
                        }
                        else if (next is >= '@' and <= '_')
                        {
                            // Other C1 7-bit pair (ESC @ through ESC _, excluding ESC [ and ESC ]).
                            // Includes DCS (ESC P), etc. Strip the pair.
                            sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);
                            i++;
                        }
                        else
                        {
                            // Other ESC sequences — strip the ESC
                            sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);
                        }
                    }
                    else
                    {
                        // Trailing ESC at end of string — strip it
                        sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);
                    }

                    break;

                case '\x07': // BEL (used as OSC terminator)
                case '\x9b': // 8-bit CSI
                case '\x9d': // 8-bit OSC
                    sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);

                    // Strip these
                    break;

                default:
                    sb?.Append (c);

                    break;
            }
        }

        return sb?.ToString () ?? renderedAnsi;
    }
}
